version: '3.8'

services:
  db:
    image: postgres
    container_name: book-my-place-db-cont
    environment:
      POSTGRES_USER: bookmyplace
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bmp
    ports:
      - "5433:5432"
    volumes:
      - /Users/vinayakbora/Documents/docker-data:/var/lib/postgresql/data
  app:
    build: .
    image: bookmyplace-app
    container_name: book-my-place-app-cont
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bmp
      SPRING_DATASOURCE_USERNAME: bookmyplace
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db
